name = "WIKI_MODULE"
description = "Query Wikipedia from within Nadybot"
version = "0.1.1"
author = "Nadyita"
github = "Nadybot/WIKI_MODULE"
bot_type = "Nadybot"
bot_version = "^6.0.0-alpha.1"

[requires]
ext-pcre = "*"
ext-json = "*"
